### ISSUE TITLE
Some actions are not working on Dedicated SQL pool

### ISSUE THREAD

**Issue by iragomez68** [pacoweb/extraSqlScriptAs#14]
Great extension. These actions are not working on dedicated SQL pool:

1. Select Top 1000
2. Edit data
3. Design   
4. Select Table as INSERT
5. Select Table as INSERT to Clipboard
6. Select Table as SELECT
7. Select Table as SELECT to Clipboard
8. Script Table as UPDATE
9. Script table as UPDATE to Clipboard
[Error.log](https://github.com/pacoweb/extraSqlScriptAs/files/9736212/Error.log)
[Design-Error.txt](https://github.com/pacoweb/extraSqlScriptAs/files/9736215/Design-Error.txt)

**Comment by pacoweb** [comment]
Thanks for the detail of the error.
Not all options are part of my extension(Select Top 1000, Edit data, Design)
I will try to reproduce the problem

**Comment by pacoweb** [comment]
Fixed by #22
