### ISSUE TITLE
Add Script table as Insert with PK 

### ISSUE THREAD

**Issue by nakawankuma** [pacoweb/extraSqlScriptAs#17]
Thank you for Good Extension.

we need 
・Script table as Insert with PK 
・Script table as Insert with PK to clipboard

I need export script ex.
SET IDENTITY_INSERT TableA OFF;
INSERT INTO TableA ( [PK], [Column1], [Column2])
Values .....
SET IDENTITY_INSERT TableA ON;

when Identity PK only. do you need?

thank you best regards.

**Comment by pacoweb** [comment]
Added new option INSERT with SET IDENTITY ON  #18
Versión 0.6.0

**Comment by nakawankuma** [comment]
Thank you for update.
I'll use this new version.
