### ISSUE TITLE
no installation proccess

### ISSUE THREAD

**Issue by vlasvlasvlas** [pacoweb/extraSqlScriptAs#3]
Hi,
i dunno how to install this, there's no option from azure data studio, only a link to github

thanks

**Comment by pacoweb** [comment]
Hi, 
When you press the install button in Azure Data Studio
it takes you to the Releases page 
and there you have to download the vsix file (https://github.com/pacoweb/extraSqlScriptAs/releases/download/0.3.0/extra-sql-script-as-0.3.0.vsix)

**Comment by vlasvlasvlas** [comment]
> 
> 
> Hi,
> When you press the install button in Azure Data Studio
> it takes you to the Releases page
> and there you have to download the vsix file (https://github.com/pacoweb/extraSqlScriptAs/releases/download/0.3.0/extra-sql-script-as-0.3.0.vsix)

yeah but then i dunno what to do with that vsix,,

**Comment by pacoweb** [comment]
Hi,
You must use the **Install from VSIX** option on extension´s section in Azure Data Studio
I paste a gif with how to do it
![install_vsix](https://user-images.githubusercontent.com/1198633/111950012-f9505c00-8ae1-11eb-979b-5b7f1d52c908.gif)

**Comment by vlasvlasvlas** [comment]
thanks! thats great :D
