### ISSUE TITLE
If first column is identity then there is an extra comma

### ISSUE THREAD

**Issue by rossdonald** [pacoweb/extraSqlScriptAs#5]
The index will be 1 when the second column is rendered and an extra comma is added.

**Comment by rossdonald** [comment]
@pacoweb I have a PR that fixes this #6

**Comment by pacoweb** [comment]
Hi,

I cannot reproduce the error. I have tried with a table whose first column is IDENTITY but I do not see the extra comma.

![cant_reproduce_error](https://user-images.githubusercontent.com/1198633/145086280-da30f4a5-f787-455a-b7ba-eb5ec115004f.gif)

**Comment by rossdonald** [comment]
Are you testing with different code?

If I look at the INSERT script js
https://github.com/pacoweb/extraSqlScriptAs/blob/fb24e1cd17be042b1165d3cb5de4695f303bd7c9/scriptInsertAs.js#L50-L51

I can see that it has code to skip Identity and Computed columns.
The logic is that when they are skipped then `i` will be greater than 0 and the seperator will be a comma for the first column that is output to the script.
