### ISSUE TITLE
DROP and CREATE

### ISSUE THREAD

**Issue by sorinc-to** [pacoweb/extraSqlScriptAs#7]
Please add Script Table as DROP and CREATE - that would be very helpful. Of course, if options for scripting all table-related objects would be present (indexes, keys, triggers, etc) would be present, it would make it great.
Thank you.

**Comment by pacoweb** [comment]
DROP and CREATE are already implemented in version 1.35.0 of Azure Data Studio
![image](https://user-images.githubusercontent.com/1198633/164989345-3306dd3b-1fef-4dbc-9281-0cf59ac742a0.png)
